### PR TITLE
Add TUN inbound for client

### PR DESCRIPTION
**Pull request by haruue**
This PR introduced TUN inbound for client, with the "system" stack from [sing-tun](https://github.com/sagernet/sing-tun).

## Configuration Example

All fields are optional except `name`.

```yaml
tun:
  name: "hytun"
  mtu: 1500
  timeout: 5m
  address:
    ipv4: 100.100.100.101/30  # An address that doesn't conflict with your local network, the prefix length must not longer than /30
    ipv6: 2001::ffff:ffff:ffff:fff1/126 # Same as above, the prefix length must not longer than /126
  route:
    ipv4: [0.0.0.0/0]
    ipv6: ["2000::/3"] # (YAML) Quotes are required for IPv6 addresses in array
    ipv4Exclude: [192.0.2.1/32] # Bypass your server's address
    ipv6Exclude: ["2001:db8::1/128"]
```

## Compatibility

| OS | Result |
|----------|--------|
| Linux 6.8 (Arch Linux latest) | :white_check_mark: OK |
| Windows 11 | :white_check_mark: IPv4 is fine. IPv6 does not work on my PC, but does on tobyxdd's side. |
| Windows 10 LTSC 2019 | :white_check_mark: Almost the same as Windows 11, except it sometimes crashes with `failed to create tun interface: Cannot create a file when that file already exists.` after client restart. |
| Windows Server 2022 | :warning: Firewall must be disabled or TCP will not work. |
| CentOS 7 | :warning: Firewall must be disabled or TCP will not work. <br/>AutoRoute is abnormal, `ipproto` matcher in `ip rule` requires [kernel v4.17](https://github.com/torvalds/linux/commit/bfff4862653bb96001ab57c1edd6d03f48e5f035), which was released on Jun 4, 2018. I won't fix this as CentOS 7 will be EOL in 103 days. CentOS 7 users may use `ip rule del from all goto 9010; ip -6 rule del from all goto 9010` or upgrade kernel to workaround this problem. |
| FreeBSD 14.0 | :x: [Not supported by sing-tun](https://github.com/apernet/sing-tun/blob/dev/tun_other.go#L10). | 

## Related Issues

close: #790 
ref: #537

### CODE REVIEW

**Comment by stqfdyr** [comment]
要有 tun 了？

**Comment by tobyxdd** [comment]
I can confirm that this works fine on macOS as well. Only the tun name must be in the format "utun"+number, otherwise it will fail with a "bad tun name" error.

**Review by tobyxdd — APPROVED** [review]

**Comment by JimmyHuang454** [comment]
@tobyxdd  this PR should not be merged, because sing-tun use GPL license.

**Comment by tobyxdd** [comment]
> @tobyxdd  this PR should not be merged, because sing-tun use GPL license.  Or client can split out as another project. 

I've got personal approval from the developer of sing-box. You can confirm with them.

**Comment by haruue** [comment]
@JimmyHuang454 

> this PR should not be merged, because sing-tun use GPL license. Or client can split out as another project.

Thank you for bringing up your concerns regarding the license compatibility. I have duly considered the implications of including code from GPL-licensed modules before implementing this PR. Specifically, the modules in question are:

+ https://github.com/SagerNet/sing-tun
+ https://github.com/SagerNet/sing

I've asked tobyxdd to contact with nekohasekai, the author of the above modules. And we've obtained a exception for the using of these modules.

Furthermore, I understand that third-party developers may have concerns about potential licensing issues resulting from dependency chains. If this is the case, I'd like to clarify that Hysteria operates as a multi-module project. For those who wish to integrate Hysteria without introducing any GPL dependencies, the recommended approach is to depend only on the core module located at `github.com/apernet/hysteria/core`. This will allow you to use the Hysteria functionality while avoiding any GPL-licensed modules. Moreover, since the code within `github.com/apernet/hysteria/app` remains under the MIT license, merging any portion of its code, excpet the TUN feature, into your own codebase should pose no licensing conflict whatsoever.

**Comment by its0ka** [comment]
tried it on armbian (debian) with linux 6.6.36 on opi pc+, default "hytun" doesn't start, reports "FATAL   failed to run TUN       {"error": "failed to create tun interface: add route 0: file exists"}", "tun0" and "utun0" work

**Pull request merged**
